### ISSUE TITLE
access denied -- https://bitbucket.org/Vardot/varbase_subprofile_basic

### ISSUE THREAD

**Issue by pricejn2** [Vardot/varbase-docs#1]
The subprofile referenced on the subpages of https://docs.varbase.vardot.com/requirements/extending-varbase/creating-a-sub-profile-from-varbase, is not accessible.

Thanks!

**Comment by pricejn2** [comment]
https://bitbucket.org/Vardot/varbase-subprofile-generator is also access denied.

**Comment by pricejn2** [comment]
Bump!

**Comment by metalbote** [comment]
Hi pricejn2,

I am working on a subprofile now for serveral months, and it is not as easy as you think, and i think, that's why varbase doesn't provide their subprofile generator to public (and support it).

Have a brief look at https://www.drupal.org/project/drupal/issues/1356276...

You can investigate acquias solution for lightning, and of course the vardoc distribution, and feel free to ask me, if you really want to dive in, be sure you do not get a simple solution, but have to get involved.

It is just not production ready... 
One funny example i ran into was that the drupal installer with subprofile patch somehow works in alphabetical order, so it worked with varbase->vardoc but with varbase->greencko not...and as you can imagine, handling config, module and profile installation, order and inheritance is not the easiest code parts...

**Comment by pricejn2** [comment]
Will research more. Thanks for the reference. 

I was curious what varbot already has given the references in this repos public documentation. If it isn't stable for public consumption yet, that's obviously fine (fantastic project imo) but docs should be updated to reflect current state.

**Comment by metalbote** [comment]
You're right, it should be commented out. As vardoc shows, and my first attempts, it was funtional a couple of months ago, but due changes in core and the "dangling" status of the subprofile patch it is not for now.
@Natshah Maybe you can publish the generator code in github/gitlab as sandbox, so we can try to adjust it again.

**Comment by Natshah** [comment]
@moerazem is the right one to be asked

**Comment by pricejn2** [comment]
My team and I are more than happy to help contribute to this effort. We're in a position of either designing a sub-profile from scratch or using what the vardot team already has started.

**Comment by HaleFx** [comment]
This is still a problem. For anyone else who stumbles on this, there are at least three repos linked in the documentation that are unavailable.

1. https://bitbucket.org/Vardot/varbase_subprofile_basic
2. https://bitbucket.org/Vardot/varbase-subprofile-basic-project
3. https://bitbucket.org/Vardot/varbase-subprofile-generator

The correct links are:
1. https://github.com/Vardot/varbase_subprofile_basic
2. https://github.com/Vardot/varbase-subprofile-basic-project
3. https://github.com/Vardot/varbase-subprofile-generator

**Comment by moerazem** [comment]
@HaleFx thanks for this. Feel free to edit the documentation directly when browsing https://docs.varbase.vardot.com/.
You can click on "Edit on GitHub" and it will file a PR.

**Comment by Natshah** [comment]
Updated the documentation pages

> The private repositories are private!
> They are only accessible if the account had a permission to access them.
> look for the public example links on github.com

**Creating A Sub Profile From Varbase**
https://docs.varbase.vardot.com/dev-docs/extending-varbase/creating-a-sub-profile-from-varbase

**Varbase Sub Profile Generator**
https://docs.varbase.vardot.com/dev-docs/extending-varbase/creating-a-sub-profile-from-varbase/varbase-sub-profile-generator

**Varbase Sub Profile Basic Template**
https://docs.varbase.vardot.com/dev-docs/extending-varbase/creating-a-sub-profile-from-varbase/varbase-sub-profile-basic-template

**Varbase Sub Profile Basic Project Template**
https://docs.varbase.vardot.com/dev-docs/extending-varbase/creating-a-sub-profile-from-varbase/varbase-sub-profile-basic-project-template

**Comment by Natshah** [comment]
Closing this issue.
Thank you for reporting and following up
